export let TrainingVocabulary;
const arrVoca = [
  {
    id: 1,
    vocabylary: "Father (Dad Daddy)",
    pronounce: "",
    semantics: "bố",
    describe: "aaaa",
  },
  {
    id: 2,
    vocabylary: "Mother (MomMum)",
    pronounce: "",
    semantics: "Mẹ",
    describe: "aaaa",
  },
  {
    id: 3,
    vocabylary: "Son",
    pronounce: "",
    semantics: "Con trai",
    describe: "aaaa",
  },
  {
    id: 4,
    vocabylary: "Daughter",
    pronounce: "",
    semantics: "Con gái",
    describe: "aaaa",
  },
  {
    id: 5,
    vocabylary: "Parent",
    pronounce: "",
    semantics: "Bố mẹ",
    describe: "aaaa",
  },
  {
    id: 6,
    vocabylary: "Child (Số nhiều là Children)",
    pronounce: "",
    semantics: "Con cái",
    describe: "aaaa",
  },
  {
    id: 7,
    vocabylary: "Husband",
    pronounce: "",
    semantics: "Chồng",
    describe: "aaaa",
  },
  {
    id: 8,
    vocabylary: "Wife",
    pronounce: "",
    semantics: "Vợ",
    describe: "aaaa",
  },
  {
    id: 9,
    vocabylary: "Brother",
    pronounce: "",
    semantics: "AnhEm trai",
    describe: "aaaa",
  },
  {
    id: 10,
    vocabylary: "Sister",
    pronounce: "",
    semantics: "ChịEm gái",
    describe: "aaaa",
  },
  {
    id: 11,
    vocabylary: "Uncle",
    pronounce: "",
    semantics: "Chú cậu bác trai",
    describe: "aaaa",
  },
  {
    id: 12,
    vocabylary: "Aunt",
    pronounce: "",
    semantics: "Cô dì bác gái",
    describe: "aaaa",
  },
  {
    id: 13,
    vocabylary: "Nephew",
    pronounce: "",
    semantics: "Cháu trai",
    describe: "aaaa",
  },
  {
    id: 14,
    vocabylary: "Niece",
    pronounce: "",
    semantics: "Cháu gái",
    describe: "aaaa",
  },
  {
    id: 15,
    vocabylary: "Cousin",
    pronounce: "",
    semantics: "Anh Chị em họ",
    describe: "aaaa",
  },
  {
    id: 16,
    vocabylary: "Grandmother (Thường gọi là: Granny, grandma)",
    pronounce: "",
    semantics: "bà",
    describe: "aaaa",
  },
  {
    id: 17,
    vocabylary: "Granny",
    pronounce: "",
    semantics: "bà",
    describe: "aaaa",
  },
  {
    id: 18,
    vocabylary: "grandma",
    pronounce: "",
    semantics: "bà ngoại",
    describe: "aaaa",
  },
  {
    id: 19,
    vocabylary: "Grandfather (Thường gọi là: grandpa)",
    pronounce: "",
    semantics: "ông",
    describe: "aaaa",
  },
  {
    id: 20,
    vocabylary: "Grandparents",
    pronounce: "",
    semantics: "Ông bà",
    describe: "aaaa",
  },
  {
    id: 21,
    vocabylary: "Boyfriend",
    pronounce: "",
    semantics: "Bạn trai",
    describe: "aaaa",
  },
  {
    id: 22,
    vocabylary: "Girlfriend",
    pronounce: "",
    semantics: "Bạn gái",
    describe: "aaaa",
  },
  {
    id: 23,
    vocabylary: "Partner",
    pronounce: "",
    semantics: "Vợ Chồng Bạn trai Bạn gái",
    describe: "aaaa",
  },
  {
    id: 24,
    vocabylary: "Godfather",
    pronounce: "",
    semantics: "Bố đỡ đầu",
    describe: "aaaa",
  },
  {
    id: 25,
    vocabylary: "Godmother",
    pronounce: "",
    semantics: "Mẹ đỡ đầu",
    describe: "aaaa",
  },
  {
    id: 26,
    vocabylary: "Godson",
    pronounce: "",
    semantics: "Con trai đỡ đầu",
    describe: "aaaa",
  },
  {
    id: 27,
    vocabylary: "Goddaughter",
    pronounce: "",
    semantics: "Con gái đỡ đầu",
    describe: "aaaa",
  },
  {
    id: 28,
    vocabylary: "Stepfather",
    pronounce: "",
    semantics: "Dượng",
    describe: "aaaa",
  },
  {
    id: 29,
    vocabylary: "Stepmother",
    pronounce: "",
    semantics: "Mẹ kế",
    describe: "aaaa",
  },
  {
    id: 30,
    vocabylary: "Half – sister",
    pronounce: "",
    semantics: "Chị em cùng cha khác mẹ cùng mẹ khác cha",
    describe: "aaaa",
  },
  {
    id: 31,
    vocabylary: "Half – brother",
    pronounce: "",
    semantics: "Anh Em cùng cha khác mẹ cùng mẹ khác cha",
    describe: "aaaa",
  },
  {
    id: 32,
    vocabylary: "Mother – in – law",
    pronounce: "",
    semantics: "Mẹ chồng vợ",
    describe: "aaaa",
  },
  {
    id: 33,
    vocabylary: "Father – in – law",
    pronounce: "",
    semantics: "Bố chồng vợ",
    describe: "aaaa",
  },
  {
    id: 34,
    vocabylary: "Son – in – law",
    pronounce: "",
    semantics: "Con rể",
    describe: "aaaa",
  },
  {
    id: 35,
    vocabylary: "Daughter – in – law",
    pronounce: "",
    semantics: "Chị em dâu",
    describe: "aaaa",
  },
  {
    id: 39,
    vocabylary: "Brother – in – law",
    pronounce: "",
    semantics: "Anh Em rể",
    describe: "aaaa",
  },
  {
    id: 37,
    vocabylary: "Bright",
    pronounce: "",
    semantics: "tươi sáng",
    describe: "aaaa",
  },
  {
    id: 38,
    vocabylary: "Breeze",
    pronounce: "",
    semantics: "cơn gió nhẹ",
    describe: "aaaa",
  },
  {
    id: 39,
    vocabylary: "Clear",
    pronounce: "",
    semantics: "trong trẻo, quang đãng",
    describe: "aaaa",
  },
  {
    id: 40,
    vocabylary: "Cloudy",
    pronounce: "",
    semantics: "trời nhiều mây",
    describe: "aaaa",
  },
  {
    id: 41,
    vocabylary: "Dry",
    pronounce: "",
    semantics: "hanh khô",
    describe: "aaaa",
  },
  {
    id: 42,
    vocabylary: "Fine",
    pronounce: "",
    semantics: "không mây, không mưa",
    describe: "aaaa",
  },
  {
    id: 43,
    vocabylary: "Foggy",
    pronounce: "",
    semantics: "có sương mù",
    describe: "aaaa",
  },
  {
    id: 44,
    vocabylary: "Haze",
    pronounce: "",
    semantics: "màn sương mỏng, thường gây ra bởi sức nóng",
    describe: "aaaa",
  },
  {
    id: 45,
    vocabylary: "Humid",
    pronounce: "",
    semantics: "(adj) ẩm",
    describe: "aaaa",
  },
  {
    id: 46,
    vocabylary: "Gloomy",
    pronounce: "",
    semantics: "(adj) ảm đạm",
    describe: "aaaa",
  },
  {
    id: 47,
    vocabylary: "Mild",
    pronounce: "",
    semantics: "(adj) ôn hòa, ấm áp",
    describe: "aaaa",
  },
  {
    id: 48,
    vocabylary: "Partially cloudy:",
    pronounce: "",
    semantics: "(adj) thời tiết có sự pha trộn giữabầu trời xanh và mây",
    describe: "aaaa",
  },
  {
    id: 49,
    vocabylary: "Overcast",
    pronounce: "",
    semantics: "(adj) âm u, tối sầm",
    describe: "aaaa",
  },
  {
    id: 50,
    vocabylary: "Sunny",
    pronounce: "",
    semantics: "(adj) nắng, có nhiều ánh nắng",
    describe: "aaaa",
  },
  {
    id: 51,
    vocabylary: "Wet",
    pronounce: "",
    semantics: "(adj) ướt sũng",
    describe: "aaaa",
  },
  {
    id: 52,
    vocabylary: "Windy",
    pronounce: "",
    semantics: "(adj) lộng gió",
    describe: "aaaa",
  },
  {
    id: 53,
    vocabylary: "blizzard",
    pronounce: "",
    semantics: "(n) cơn bão tuyết",
    describe: "aaaa",
  },
  {
    id: 54,
    vocabylary: "blustery",
    pronounce: "",
    semantics: "(n) cơn gió mạnh",
    describe: "aaaa",
  },
  {
    id: 55,
    vocabylary: "damp",
    pronounce: "",
    semantics: "(n) không khí ẩm thấp, ẩm ướt",
    describe: "aaaa",
  },
  {
    id: 56,
    vocabylary: "drizzle",
    pronounce: "",
    semantics: "(n) cơn mưa phùn",
    describe: "aaaa",
  },
  {
    id: 57,
    vocabylary: "flood",
    pronounce: "",
    semantics: "(n) lũ lụt",
    describe: "aaaa",
  },
  {
    id: 58,
    vocabylary: "hail",
    pronounce: "",
    semantics: "(n) mưa đá",
    describe: "aaaa",
  },
  {
    id: 59,
    vocabylary: "hurricane",
    pronounce: "",
    semantics: "(n) siêu bão",
    describe: "aaaa",
  },
  {
    id: 60,
    vocabylary: "gale",
    pronounce: "",
    semantics: "(n) gió giật",
    describe: "aaaa",
  },
  {
    id: 61,
    vocabylary: "rain",
    pronounce: "",
    semantics: "(n) cơn mưa",
    describe: "aaaa",
  },
  {
    id: 62,
    vocabylary: "rainbow",
    pronounce: "",
    semantics: "(n) cầu vồng",
    describe: "aaaa",
  },
  {
    id: 63,
    vocabylary: "rainstorm",
    pronounce: "",
    semantics: "(n) mưa bão",
    describe: "aaaa",
  },
  {
    id: 64,
    vocabylary: "mist",
    pronounce: "",
    semantics: "(n) sương muối",
    describe: "aaaa",
  },
  {
    id: 65,
    vocabylary: "lightning",
    pronounce: "",
    semantics: "(n) tia chớp",
    describe: "aaaa",
  },
  {
    id: 66,
    vocabylary: "thunder",
    pronounce: "",
    semantics: "(n) sấm sét",
    describe: "aaaa",
  },
  {
    id: 67,
    vocabylary: "thunderstorm",
    pronounce: "",
    semantics: "(n) bão tố kèm sấm sét, cơn giông",
    describe: "aaaa",
  },
  {
    id: 68,
    vocabylary: "shower",
    pronounce: "",
    semantics: "(n) cơn mưa rào",
    describe: "aaaa",
  },
  {
    id: 69,
    vocabylary: "snow",
    pronounce: "",
    semantics: "tuyết",
    describe: "aaaa",
  },
  {
    id: 70,
    vocabylary: "snowflake",
    pronounce: "",
    semantics: "(n) bông hoa tuyết",
    describe: "aaaa",
  },
  {
    id: 71,
    vocabylary: "snowstorm",
    pronounce: "",
    semantics: "(n) cơn bão tuyết",
    describe: "aaaa",
  },
  {
    id: 72,
    vocabylary: "storm",
    pronounce: "",
    semantics: "(n) cơn bão",
    describe: "aaaa",
  },
  {
    id: 73,
    vocabylary: "typhoon",
    pronounce: "",
    semantics: "(n) bão lớn",
    describe: "aaaa",
  },
  {
    id: 74,
    vocabylary: "tornado",
    pronounce: "",
    semantics: "(n) lốc xoáy",
    describe: "aaaa",
  },
  {
    id: 75,
    vocabylary: "weather forecast:",
    pronounce: "",
    semantics: "(n) sự dự báo thời tiết",
    describe: "aaaa",
  },
  {
    id: 76,
    vocabylary: "downpour",
    pronounce: "",
    semantics: "(n) trận mưa như trút nước xuống",
    describe: "aaaa",
  },
  {
    id: 77,
    vocabylary: "rainfall",
    pronounce: "",
    semantics: "(n) lượng mưa, trận mưa rào",
    describe: "aaaa",
  },
  {
    id: 78,
    vocabylary: "torrential rain",
    pronounce: "",
    semantics: "(n) lượng mưa lớn như thác đổ",
    describe: "aaaa",
  },
  {
    id: 79,
    vocabylary: "CV (viết tắt của curriculum vitae)",
    pronounce: "",
    semantics: "sơ yếu lý lịch",
    describe: "aaaa",
  },
  {
    id: 80,
    vocabylary: "Application form",
    pronounce: "",
    semantics: "đơn xin việc",
    describe: "aaaa",
  },
  {
    id: 81,
    vocabylary: "Interview",
    pronounce: "",
    semantics: "phỏng vấn",
    describe: "aaaa",
  },
  {
    id: 82,
    vocabylary: "Job",
    pronounce: "",
    semantics: "việc làm",
    describe: "aaaa",
  },
  {
    id: 83,
    vocabylary: "Career",
    pronounce: "",
    semantics: "nghề nghiệp",
    describe: "aaaa",
  },
  {
    id: 84,
    vocabylary: "Part-time",
    pronounce: "",
    semantics: "bán thời gian",
    describe: "aaaa",
  },
  {
    id: 85,
    vocabylary: "Full-time",
    pronounce: "",
    semantics: "toàn thời gian",
    describe: "aaaa",
  },
  {
    id: 86,
    vocabylary: "Permanent",
    pronounce: "",
    semantics: "dài hạn",
    describe: "aaaa",
  },
  {
    id: 87,
    vocabylary: "Temporary",
    pronounce: "",
    semantics: "tạm thời",
    describe: "aaaa",
  },
  {
    id: 88,
    vocabylary: "Appointment",
    pronounce: "",
    semantics: "buổi hẹn gặp",
    describe: "aaaa",
  },
  {
    id: 89,
    vocabylary: "Ad or advert",
    pronounce: "",
    semantics: "quảng cáo",
    describe: "aaaa",
  },
  {
    id: 90,
    vocabylary: "Contract",
    pronounce: "",
    semantics: "hợp đồng",
    describe: "aaaa",
  },
  {
    id: 91,
    vocabylary: "Notice period",
    pronounce: "",
    semantics: "thời gian thông báo nghỉ việc",
    describe: "aaaa",
  },
  {
    id: 92,
    vocabylary: "Holiday entitlement",
    pronounce: "",
    semantics: "chế độ ngày nghỉ được hưởng",
    describe: "aaaa",
  },
  {
    id: 93,
    vocabylary: "Sick pay",
    pronounce: "",
    semantics: "tiền lương ngày ốm",
    describe: "aaaa",
  },
  {
    id: 94,
    vocabylary: "Holiday pay",
    pronounce: "",
    semantics: "tiền lương ngày nghỉ",
    describe: "aaaa",
  },
  {
    id: 95,
    vocabylary: "Overtime",
    pronounce: "",
    semantics: "ngoài giờ làm việc",
    describe: "aaaa",
  },
];
